# Generated by Django 6.0.5 on 2026-05-29 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExceptionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('type', models.CharField(choices=[('stock', '库存异常'), ('order', '订单异常'), ('duplicate', '重复记录'), ('appeal', '用户申诉'), ('other', '其他')], max_length=20, verbose_name='异常类型')),
                ('description', models.TextField(verbose_name='异常描述')),
                ('related_id', models.CharField(blank=True, default='', max_length=50, verbose_name='关联ID')),
                ('status', models.CharField(choices=[('open', '待处理'), ('processing', '处理中'), ('resolved', '已解决')], default='open', max_length=20, verbose_name='状态')),
                ('result', models.TextField(blank=True, default='', verbose_name='处理结果')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
            ],
            options={
                'verbose_name': '异常工单',
                'verbose_name_plural': '异常工单',
                'db_table': 'exception_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OpLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('operator', models.CharField(max_length=100, verbose_name='操作人')),
                ('action', models.CharField(max_length=50, verbose_name='操作类型')),
                ('target', models.CharField(max_length=200, verbose_name='操作对象')),
                ('detail', models.TextField(blank=True, default='', verbose_name='操作详情')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'db_table': 'operation_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RuleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('recycle_rate', models.PositiveIntegerField(default=30, verbose_name='回收返还比例(%)')),
                ('new_user_points', models.PositiveIntegerField(default=500, verbose_name='新用户赠送积分')),
                ('max_draw_per_day', models.PositiveIntegerField(default=20, verbose_name='每日抽取上限')),
                ('min_points_to_draw', models.PositiveIntegerField(default=60, verbose_name='最低抽取积分')),
                ('order_auto_confirm_days', models.PositiveIntegerField(default=7, verbose_name='订单自动确认天数')),
                ('exchange_lock_hours', models.PositiveIntegerField(default=48, verbose_name='换物锁定时长(小时)')),
                ('updated_by', models.CharField(blank=True, default='', max_length=100, verbose_name='修改人')),
            ],
            options={
                'verbose_name': '规则配置',
                'verbose_name_plural': '规则配置',
                'db_table': 'rule_config',
            },
        ),
        migrations.CreateModel(
            name='TransactionLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('type', models.CharField(choices=[('blindbox_draw', '盲抽'), ('recycle', '回收'), ('shipment', '发货'), ('exchange', '换物'), ('system', '系统')], max_length=20, verbose_name='交易类型')),
                ('description', models.CharField(max_length=500, verbose_name='说明')),
                ('amount', models.IntegerField(default=0, verbose_name='积分变动')),
            ],
            options={
                'verbose_name': '交易账本',
                'verbose_name_plural': '交易账本',
                'db_table': 'transaction_ledger',
                'ordering': ['-created_at'],
            },
        ),
    ]
