# Generated by Django 6.0.5 on 2026-05-29 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, verbose_name='商家名称')),
                ('contact_name', models.CharField(max_length=50, verbose_name='联系人')),
                ('phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('email', models.EmailField(blank=True, default='', max_length=100, verbose_name='联系邮箱')),
                ('license', models.CharField(blank=True, default='', max_length=200, verbose_name='营业执照编号')),
                ('business_scope', models.TextField(blank=True, default='', verbose_name='经营范围')),
                ('supply_desc', models.TextField(blank=True, default='', verbose_name='供货说明')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已驳回'), ('frozen', '已冻结')], default='pending', max_length=20, verbose_name='状态')),
                ('credit_score', models.IntegerField(default=100, verbose_name='信用评分')),
                ('review_note', models.TextField(blank=True, default='', verbose_name='审核意见')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merchant', to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '商家',
                'verbose_name_plural': '商家',
                'db_table': 'merchant',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, verbose_name='商品名称')),
                ('image', models.CharField(max_length=500, verbose_name='商品图片')),
                ('category', models.CharField(max_length=50, verbose_name='分类')),
                ('rarity', models.CharField(choices=[('N', 'N'), ('R', 'R'), ('SR', 'SR'), ('SSR', 'SSR')], max_length=10, verbose_name='稀有度')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('estimated_points', models.PositiveIntegerField(default=0, verbose_name='预估积分')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已驳回'), ('offline', '已下架')], default='pending', max_length=20, verbose_name='状态')),
                ('review_note', models.TextField(blank=True, default='', verbose_name='审核意见')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='merchant.merchant', verbose_name='所属商家')),
            ],
            options={
                'verbose_name': '商家商品',
                'verbose_name_plural': '商家商品',
                'db_table': 'merchant_product',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('type', models.CharField(choices=[('increase', '入库'), ('decrease', '出库'), ('modify', '调整')], max_length=20, verbose_name='变动类型')),
                ('before_stock', models.PositiveIntegerField(verbose_name='变动前库存')),
                ('after_stock', models.PositiveIntegerField(verbose_name='变动后库存')),
                ('reason', models.CharField(blank=True, default='', max_length=200, verbose_name='变动原因')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_records', to='merchant.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '库存变动记录',
                'verbose_name_plural': '库存变动记录',
                'db_table': 'merchant_inventory_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('current_stock', models.PositiveIntegerField(default=0, verbose_name='当前库存')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='merchant.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '库存',
                'verbose_name_plural': '库存',
                'db_table': 'merchant_inventory',
            },
        ),
        migrations.CreateModel(
            name='ShipmentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('task_no', models.CharField(max_length=50, verbose_name='任务编号')),
                ('order_no', models.CharField(max_length=50, verbose_name='关联订单号')),
                ('receiver_name', models.CharField(max_length=30, verbose_name='收货人')),
                ('receiver_phone', models.CharField(max_length=11, verbose_name='收货电话')),
                ('receiver_address', models.TextField(verbose_name='收货地址')),
                ('status', models.CharField(choices=[('pending', '待发货'), ('shipped', '已发货')], default='pending', max_length=20, verbose_name='状态')),
                ('logistics_company', models.CharField(blank=True, default='', max_length=100, verbose_name='物流公司')),
                ('tracking_no', models.CharField(blank=True, default='', max_length=100, verbose_name='运单号')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='发货时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='merchant.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '发货任务',
                'verbose_name_plural': '发货任务',
                'db_table': 'merchant_shipment',
                'ordering': ['-created_at'],
            },
        ),
    ]
