# Generated by Django 6.0.5 on 2026-05-29 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('asset_name', models.CharField(max_length=100, verbose_name='资产名称')),
                ('asset_image', models.CharField(max_length=500, verbose_name='资产图片')),
                ('asset_rarity', models.CharField(choices=[('N', 'N'), ('R', 'R'), ('SR', 'SR'), ('SSR', 'SSR')], max_length=10, verbose_name='资产稀有度')),
                ('asset_category', models.CharField(max_length=50, verbose_name='资产分类')),
                ('expect_description', models.TextField(verbose_name='期望换取的物品描述')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('status', models.CharField(choices=[('published', '发布中'), ('locked', '已锁定'), ('completed', '已完成'), ('cancelled', '已取消')], default='published', max_length=20, verbose_name='状态')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_posts', to='assets.asset', verbose_name='交换资产')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_posts', to=settings.AUTH_USER_MODEL, verbose_name='发布人')),
            ],
            options={
                'verbose_name': '换物帖子',
                'verbose_name_plural': '换物帖子',
                'db_table': 'exchange_post',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('applicant_asset_name', models.CharField(max_length=100, verbose_name='申请人资产名称')),
                ('applicant_asset_image', models.CharField(max_length=500, verbose_name='申请人资产图片')),
                ('applicant_asset_rarity', models.CharField(max_length=10, verbose_name='申请人资产稀有度')),
                ('post_asset_name', models.CharField(max_length=100, verbose_name='目标资产名称')),
                ('post_asset_image', models.CharField(max_length=500, verbose_name='目标资产图片')),
                ('post_asset_rarity', models.CharField(max_length=10, verbose_name='目标资产稀有度')),
                ('remark', models.TextField(blank=True, default='', verbose_name='申请备注')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('accepted', '已接受'), ('rejected', '已拒绝'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_applications', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('applicant_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_applications', to='assets.asset', verbose_name='申请人资产')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='exchange.exchangepost', verbose_name='换物帖子')),
            ],
            options={
                'verbose_name': '换物申请',
                'verbose_name_plural': '换物申请',
                'db_table': 'exchange_application',
                'ordering': ['-created_at'],
            },
        ),
    ]
