# Generated by Django 6.0.5 on 2026-05-29 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('balance', models.IntegerField(default=0, verbose_name='积分余额')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='points_account', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '积分账户',
                'verbose_name_plural': '积分账户',
                'db_table': 'points_account',
            },
        ),
        migrations.CreateModel(
            name='PointsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('type', models.CharField(choices=[('blindbox_consume', '盲盒消耗'), ('recycle_return', '回收返还'), ('system_adjust', '系统调整')], max_length=30, verbose_name='变动类型')),
                ('amount', models.IntegerField(verbose_name='变动积分')),
                ('balance', models.IntegerField(verbose_name='变动后余额')),
                ('description', models.CharField(max_length=200, verbose_name='说明')),
                ('related_id', models.CharField(blank=True, default='', max_length=50, verbose_name='关联业务ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_records', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '积分流水',
                'verbose_name_plural': '积分流水',
                'db_table': 'points_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('type', models.CharField(choices=[('blindbox_draw', '盲盒抽取'), ('recycle', '回收'), ('shipment', '发货'), ('exchange', '换物')], max_length=30, verbose_name='交易类型')),
                ('description', models.CharField(max_length=200, verbose_name='说明')),
                ('related_asset_name', models.CharField(max_length=100, verbose_name='关联资产名称')),
                ('status_change', models.CharField(max_length=100, verbose_name='状态变更')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_records', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '交易记录',
                'verbose_name_plural': '交易记录',
                'db_table': 'transaction_record',
                'ordering': ['-created_at'],
            },
        ),
    ]
