# Generated by Django 6.0.5 on 2026-05-29 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlindBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, verbose_name='盲盒名称')),
                ('cover', models.CharField(max_length=500, verbose_name='封面图')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('category', models.CharField(max_length=50, verbose_name='分类')),
                ('cost_points', models.PositiveIntegerField(verbose_name='消耗积分')),
                ('status', models.CharField(choices=[('active', '上架中'), ('inactive', '已下架'), ('ended', '已结束')], default='inactive', max_length=20, verbose_name='状态')),
                ('start_time', models.DateTimeField(verbose_name='活动开始时间')),
                ('end_time', models.DateTimeField(verbose_name='活动结束时间')),
            ],
            options={
                'verbose_name': '盲盒',
                'verbose_name_plural': '盲盒',
                'db_table': 'blindbox',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='奖品名称')),
                ('image', models.CharField(max_length=500, verbose_name='奖品图片')),
                ('rarity', models.CharField(choices=[('N', 'N'), ('R', 'R'), ('SR', 'SR'), ('SSR', 'SSR')], max_length=10, verbose_name='稀有度')),
                ('probability', models.PositiveIntegerField(verbose_name='概率(%)')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='库存')),
                ('blindbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='blindbox.blindbox', verbose_name='所属盲盒')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prizes', to='merchant.product', verbose_name='关联商品')),
            ],
            options={
                'verbose_name': '奖品',
                'verbose_name_plural': '奖品',
                'db_table': 'blindbox_prize',
                'ordering': ['rarity'],
            },
        ),
        migrations.CreateModel(
            name='DrawRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('prize_name', models.CharField(max_length=100, verbose_name='奖品名称（快照）')),
                ('prize_image', models.CharField(max_length=500, verbose_name='奖品图片（快照）')),
                ('rarity', models.CharField(max_length=10, verbose_name='稀有度（快照）')),
                ('cost_points', models.PositiveIntegerField(verbose_name='消耗积分')),
                ('blindbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draw_records', to='blindbox.blindbox', verbose_name='盲盒')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draw_records', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('prize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draw_records', to='blindbox.prize', verbose_name='抽中奖品')),
            ],
            options={
                'verbose_name': '抽盒记录',
                'verbose_name_plural': '抽盒记录',
                'db_table': 'blindbox_draw_record',
                'ordering': ['-created_at'],
            },
        ),
    ]
