# Generated by Django 6.0.6 on 2026-06-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blindbox", "0003_prize_probability_decimal"),
    ]

    operations = [
        migrations.AddField(
            model_name="prize",
            name="available_for_shipping",
            field=models.PositiveIntegerField(
                default=0,
                help_text="商家实际可发货的库存数量",
                verbose_name="可发货数量",
            ),
        ),
        migrations.AddField(
            model_name="prize",
            name="pending_shipment_count",
            field=models.PositiveIntegerField(
                default=0, help_text="已抽奖但未发货的数量", verbose_name="待发货数量"
            ),
        ),
        migrations.AlterField(
            model_name="drawrecord",
            name="draw_status",
            field=models.CharField(
                choices=[
                    ("success", "成功"),
                    ("failed", "失败"),
                    ("pending_shipment", "待发货"),
                    ("shipped", "已发货"),
                ],
                default="success",
                max_length=20,
                verbose_name="抽取状态",
            ),
        ),
    ]
