# Generated by Django 6.0.5 on 2026-06-07 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('order_no', models.CharField(max_length=50, unique=True, verbose_name='订单编号')),
                ('type', models.CharField(choices=[('shipment', '发货'), ('exchange', '换物')], max_length=20, verbose_name='订单类型')),
                ('asset_name', models.CharField(max_length=100, verbose_name='资产名称')),
                ('asset_image', models.CharField(max_length=500, verbose_name='资产图片')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('shipped', '已发货'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='状态')),
                ('receiver_name', models.CharField(max_length=30, verbose_name='收货人')),
                ('receiver_phone', models.CharField(max_length=11, verbose_name='收货电话')),
                ('receiver_address', models.TextField(verbose_name='收货地址')),
                ('logistics_company', models.CharField(blank=True, default='', max_length=100, verbose_name='物流公司')),
                ('tracking_no', models.CharField(blank=True, default='', max_length=100, verbose_name='运单号')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='发货时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='assets.asset', verbose_name='关联资产')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'db_table': 'order',
                'ordering': ['-created_at'],
            },
        ),
    ]
