# Generated by Django 6.0.5 on 2026-06-07 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blindbox', '0001_initial'),
        ('merchant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('product_name', models.CharField(max_length=100, verbose_name='商品名称')),
                ('product_image', models.CharField(max_length=500, verbose_name='商品图片')),
                ('category', models.CharField(max_length=50, verbose_name='分类')),
                ('rarity', models.CharField(choices=[('N', 'N'), ('R', 'R'), ('SR', 'SR'), ('SSR', 'SSR')], max_length=10, verbose_name='稀有度')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('source_type', models.CharField(choices=[('blindbox', '盲盒抽取'), ('exchange', '换物获得')], max_length=20, verbose_name='来源类型')),
                ('source_name', models.CharField(max_length=100, verbose_name='来源名称')),
                ('obtained_at', models.DateTimeField(verbose_name='获得时间')),
                ('status', models.CharField(choices=[('available', '可操作'), ('exchange_published', '换物发布中'), ('exchange_locked', '换物锁定中'), ('pending_shipment', '待发货'), ('shipped', '已发货'), ('recycled', '已回收'), ('completed', '已完成')], default='available', max_length=30, verbose_name='状态')),
                ('estimated_points', models.PositiveIntegerField(default=0, verbose_name='估值积分')),
                ('recyclable_points', models.PositiveIntegerField(default=0, verbose_name='可回收积分')),
                ('draw_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='blindbox.drawrecord', verbose_name='抽盒记录')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='merchant.product', verbose_name='关联商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户资产',
                'verbose_name_plural': '用户资产',
                'db_table': 'user_asset',
                'ordering': ['-obtained_at'],
            },
        ),
    ]
